source :rubygems

require File.expand_path('../../sunspot/lib/sunspot/version', __FILE__)

gem 'sunspot_solr', Sunspot::VERSION, :path => File.expand_path('../../sunspot_solr', __FILE__)

group :test do
  gem 'rspec', '~> 1.3'
  gem 'ruby-debug'
end
