source :rubygems

require File.expand_path('../lib/sunspot/version', __FILE__)

gem 'sunspot', Sunspot::VERSION, :path => File.expand_path('..', __FILE__)
gem 'sunspot_solr', Sunspot::VERSION, :path => File.expand_path('../../sunspot_solr', __FILE__)

group :test do
  gem 'rspec', '~> 1.3'
  gem 'ruby-debug'
end

gem 'hanna'
